services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
    depends_on:
      - db
    networks:
      - config-store-net
  db:
    image: postgres:17.1
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
    networks:
      - config-store-net

networks:
  config-store-net:
    driver: bridge

volumes:
  db_data: